name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install fyne-cross
      run: |
        go install github.com/fyne-io/fyne-cross@latest

    - name: Build binaries
      run: |
        fyne-cross linux \
          --arch amd64 --output "build/app-linux-amd64"
        fyne-cross windows \
          --arch amd64 --output "build/app-windows-amd64.exe"
        fyne-cross darwin \
          --arch arm64 --output "build/app-macos-arm64"
        fyne-cross darwin \
          --arch amd64 --output "build/app-macos-amd64"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-binaries
        path: build/
